### ISSUE TITLE
SSB keeps asking for access to contacts

### ISSUE THREAD

**Issue by hannestyden** [lhl/chrome-ssb-osx#28]
Every time I restart an SSB created with the script (and search in Gmail) I get this dialog:
![](https://cloud.githubusercontent.com/assets/9516/3077191/bd498b36-e418-11e3-84ef-758ba450909c.png)

It doesn't matter if I answer "Don't Allow" or "OK", my preference is not saved.

Does anyone know a way I could persist my preference? Thanks.

**Comment by hannestyden** [comment]
Closing this since I forgot I had opened it.

**Comment by lhl** [comment]
Did this ever get fixed or was there an alternative? I have given this script much love since I switched to Linux for my day-to-day and wrote pyssb to fulfill my ssb needs.

**Comment by lhl** [comment]
Oh ha mm, apparently I had updated pointing some alternatives last year. Carry on.
